name: Repository check
on: push

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint_actionlint:
    name: Lint with actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: devops-actions/actionlint@v0.1.3
  lint_prettier:
    name: Lint with prettier
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: creyD/prettier_action@v4.3
        with:
          dry: true
          clean_node_folder: false
          prettier_options: --write .