name: Repository check
on: push

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint_actionlint:
    name: Lint with actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: devops-actions/actionlint@e7ee33fbf5aa8c9f9ee1145137f3e52e25d6a35b # v0.1.3
  lint_prettier:
    name: Lint with prettier
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          dry: true
          clean_node_folder: false
          prettier_options: --write .
  lint_renovate:
    name: Lint with renovate config validator
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    container:
      image: ghcr.io/renovatebot/renovate:39
      options: --user root
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Lint renovate configs
        run: |
          renovate-config-validator --strict "$RENOVATE_CONFIGS"
        env:
          RENOVATE_CONFIGS: |
            renovate.json
            configs/akontainers.gitlab.json
            configs/atemplates.gitlab.json
  lint_renovate_alternative:
    name:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
        with:
          strict: true
          config_file_path: |
            renovate.json
            configs/akontainers.gitlab.json
            configs/atemplates.gitlab.json